name: job
on: workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - run: |
             echo "hello world"
             echo "world2"

  test:
   runs-on: ubuntu-latest
   steps:
    - run: |
             echo "hello world"
             echo "world2"

  
  deploy:
   runs-on: ubuntu-latest
   steps:
    - run: |
             echo "hello world"
             echo "world2"
